// <auto-generated />
using System;
using MarysMajesticMovies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarysMajesticMovies.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarysMajesticMovies.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedToStoreDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ImdbRating")
                        .HasColumnType("float");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<int>("NoOfOrders")
                        .HasColumnType("int");

                    b.Property<string>("Plot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RunTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actors = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 787, DateTimeKind.Local).AddTicks(8754),
                            Director = "Christopher Nolan",
                            Genre = "Action, Adventure, Sci-Fi",
                            ImdbId = "tt1375666",
                            ImdbRating = 8.8000000000000007,
                            InStock = 7,
                            NoOfOrders = 0,
                            Plot = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg",
                            Price = 149.0,
                            RunTime = "148",
                            Title = "Inception",
                            TrailerUrl = "https://www.youtube.com/embed/YoHD9XEInc0",
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            Actors = "Helena Bergström, Rikard Wolff, Sven Wollter",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5335),
                            Director = "Colin Nutley",
                            Genre = "Comedy, Drama",
                            ImdbId = "tt0105916",
                            ImdbRating = 6.2999999999999998,
                            InStock = 5,
                            NoOfOrders = 0,
                            Plot = "A rural village is divided when an extraordinary couple move into a mansion.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNmE5ZjM3MDgtNmY5My00Y2JiLThmNDItZjU2NjIwNTYyNTdjXkEyXkFqcGdeQXVyNzQxNDExNTU@._V1_.jpg",
                            Price = 99.0,
                            RunTime = "119",
                            Title = "Änglagård",
                            TrailerUrl = "https://www.youtube.com/embed/NsvkwMTXzOI",
                            Year = 1992
                        },
                        new
                        {
                            Id = 3,
                            Actors = "Sam Neill, Laura Dern, Jeff Goldblum",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5377),
                            Director = "Steven Spielberg",
                            Genre = "Action, Aventure, Sci-Fi",
                            ImdbId = "tt0107290",
                            ImdbRating = 8.0999999999999996,
                            InStock = 12,
                            NoOfOrders = 0,
                            Plot = "A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_.jpg",
                            Price = 129.0,
                            RunTime = "127",
                            Title = "Jurrasic Park",
                            TrailerUrl = "https://www.youtube.com/embed/KdGO9tL2DQ4",
                            Year = 1993
                        },
                        new
                        {
                            Id = 4,
                            Actors = "Elijah Wood, Ian McKellen, Orlando Bloom",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5385),
                            Director = "Peter Jackson",
                            Genre = "Action, Aventure, Drama",
                            ImdbId = "tt0120737",
                            ImdbRating = 8.8000000000000007,
                            InStock = 5,
                            NoOfOrders = 0,
                            Plot = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY999_CR0,0,673,999_AL_.jpg",
                            Price = 129.0,
                            RunTime = "178",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            TrailerUrl = "https://www.youtube.com/embed/V75dMMIW2B4",
                            Year = 2001
                        },
                        new
                        {
                            Id = 5,
                            Actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5390),
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Genre = "Action, Sci-Fi",
                            ImdbId = "tt0133093",
                            ImdbRating = 8.6999999999999993,
                            InStock = 18,
                            NoOfOrders = 0,
                            Plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,665,1000_AL_.jpg",
                            Price = 79.0,
                            RunTime = "136",
                            Title = "The Matrix",
                            TrailerUrl = "https://www.youtube.com/embed/m8e-FF8MsqU",
                            Year = 1999
                        },
                        new
                        {
                            Id = 6,
                            Actors = "Hugo Weaving, Natalie Portman, Rupert Graves",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5395),
                            Director = "James McTeigue",
                            Genre = "Action, Drama, Sci-Fi",
                            ImdbId = "tt0434409",
                            ImdbRating = 8.1999999999999993,
                            InStock = 19,
                            NoOfOrders = 0,
                            Plot = "In a future British tyranny, a shadowy freedom fighter, known only by the alias of 'V', plots to overthrow it with the help of a young woman.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg",
                            Price = 139.0,
                            RunTime = "132",
                            Title = "V for Vendetta",
                            TrailerUrl = "https://www.youtube.com/embed/lSA7mAHolAw",
                            Year = 2005
                        },
                        new
                        {
                            Id = 7,
                            Actors = "Tatsuya Fujiwara, Aki Maeda, Tarô Yamamoto",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5401),
                            Director = "Kinji Fukusaku",
                            Genre = "Adventure, Drama, Sci-Fi",
                            ImdbId = "tt0266308",
                            ImdbRating = 7.5999999999999996,
                            InStock = 11,
                            NoOfOrders = 0,
                            Plot = "In the future, the Japanese government captures a class of ninth-grade students and forces them to kill each other under the revolutionary 'Battle Royale' act.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMDc2MGYwYzAtNzE2Yi00YmU3LTkxMDUtODk2YjhiNDM5NDIyXkEyXkFqcGdeQXVyMTEwNDU1MzEy._V1_SY1000_CR0,0,666,1000_AL_.jpg",
                            Price = 159.0,
                            RunTime = "116",
                            Title = "Battle Royale",
                            TrailerUrl = "https://www.youtube.com/embed/N0p1t-dC7Ko",
                            Year = 2000
                        },
                        new
                        {
                            Id = 8,
                            Actors = "Robin Williams, Robert Sean Leonard, Ethan Hawke",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5405),
                            Director = "Peter Weir",
                            Genre = "Comedy, Drama",
                            ImdbId = "tt0097165",
                            ImdbRating = 8.0999999999999996,
                            InStock = 5,
                            NoOfOrders = 0,
                            Plot = "English teacher John Keating inspires his students to look at poetry with a different perspective of authentic knowledge and feelings.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BOGYwYWNjMzgtNGU4ZC00NWQ2LWEwZjUtMzE1Zjc3NjY3YTU1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY1000_CR0,0,677,1000_AL_.jpg",
                            Price = 79.0,
                            RunTime = "128",
                            Title = "Dead Poets Society",
                            TrailerUrl = "https://www.youtube.com/embed/ye4KFyWu2do",
                            Year = 1989
                        },
                        new
                        {
                            Id = 9,
                            Actors = "Liam Neeson, Ralph Fiennes, Ben Kingsley",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5410),
                            Director = "Steven Spielberg",
                            Genre = "Biography, Drama, History",
                            ImdbId = "tt0108052",
                            ImdbRating = 8.9000000000000004,
                            InStock = 13,
                            NoOfOrders = 0,
                            Plot = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,666,1000_AL_.jpg",
                            Price = 129.0,
                            RunTime = "195",
                            Title = "Schindler's List",
                            TrailerUrl = "https://www.youtube.com/embed/gG22XNhtnoY",
                            Year = 1993
                        },
                        new
                        {
                            Id = 10,
                            Actors = "David Sandberg, Jorma Taccone, Steven Chew",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5414),
                            Director = "David Sandberg",
                            Genre = "Short, Action, Comedy",
                            ImdbId = "tt3472226",
                            ImdbRating = 8.0,
                            InStock = 73,
                            NoOfOrders = 0,
                            Plot = "In 1985, Kung Fury, the toughest martial artist cop in Miami, goes back in time to kill the worst criminal of all time - Kung Führer, a.k.a. Adolf Hitler.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjQwMjU2ODU5NF5BMl5BanBnXkFtZTgwNTU1NjM4NTE@._V1_SY999_CR0,0,702,999_AL_.jpg",
                            Price = 229.0,
                            RunTime = "31",
                            Title = "Kung Fury",
                            TrailerUrl = "https://www.youtube.com/embed/89AxvewTS90",
                            Year = 2015
                        },
                        new
                        {
                            Id = 11,
                            Actors = "Jean Reno, Gary Oldman, Natalie Portman",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5419),
                            Director = "Luc Besson",
                            Genre = "Action, Crime, Drama",
                            ImdbId = "tt0110413",
                            ImdbRating = 8.5,
                            InStock = 11,
                            NoOfOrders = 0,
                            Plot = "Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BZDAwYTlhMDEtNTg0OS00NDY2LWJjOWItNWY3YTZkM2UxYzUzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY1000_CR0,0,710,1000_AL_.jpg",
                            Price = 99.0,
                            RunTime = "110",
                            Title = "Leon",
                            TrailerUrl = "https://www.youtube.com/embed/jawVxq1Iyl0",
                            Year = 1994
                        },
                        new
                        {
                            Id = 12,
                            Actors = "Elijah Wood, Ian McKellen, Viggo Mortensen",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5423),
                            Director = "Peter Jackson",
                            Genre = "Adventure, Drama, Fantasy",
                            ImdbId = "tt0167261",
                            ImdbRating = 8.6999999999999993,
                            InStock = 22,
                            NoOfOrders = 0,
                            Plot = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNGE5MzIyNTAtNWFlMC00NDA2LWJiMjItMjc4Yjg1OWM5NzhhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,684,1000_AL_.jpg",
                            Price = 129.0,
                            RunTime = "179",
                            Title = "The Lord of the Rings: The Two Towers",
                            TrailerUrl = "https://www.youtube.com/embed/hYcw5ksV8YQ",
                            Year = 2002
                        },
                        new
                        {
                            Id = 13,
                            Actors = "Elijah Wood, Viggo Mortensen, Ian McKellen",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5428),
                            Director = "Peter Jackson",
                            Genre = "Adventure, Drama, Fantasy",
                            ImdbId = "tt0167260",
                            ImdbRating = 8.9000000000000004,
                            InStock = 15,
                            NoOfOrders = 0,
                            Plot = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,675,1000_AL_.jpg",
                            Price = 129.0,
                            RunTime = "201",
                            Title = "The Lord of the Rings: The Return of the King",
                            TrailerUrl = "https://www.youtube.com/embed/r5X-hFf6Bwo",
                            Year = 2003
                        },
                        new
                        {
                            Id = 14,
                            Actors = "Arnold Schwarzenegger, Linda Hamilton, Michael Biehn",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5432),
                            Director = "James Cameron",
                            Genre = "Action, Sci-Fi",
                            ImdbId = "tt0088247",
                            ImdbRating = 8.0,
                            InStock = 17,
                            NoOfOrders = 0,
                            Plot = "In 1984, a human soldier is tasked to stop an indestructible cyborg killing machine, both sent from 2029, from executing a young woman, whose unborn son is the key to humanity's future salvation.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,666,1000_AL_.jpg",
                            Price = 89.0,
                            RunTime = "107",
                            Title = "Terminator",
                            TrailerUrl = "https://www.youtube.com/embed/k64P4l2Wmeg",
                            Year = 1984
                        },
                        new
                        {
                            Id = 15,
                            Actors = "Scarlett Johansson, Morgan Freeman, Min-Sik Choi",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5437),
                            Director = "Luc Besson",
                            Genre = "Action, Sci-Fi, Thriller",
                            ImdbId = "tt2872732",
                            ImdbRating = 6.4000000000000004,
                            InStock = 19,
                            NoOfOrders = 0,
                            Plot = "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic. ",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BODcxMzY3ODY1NF5BMl5BanBnXkFtZTgwNzg1NDY4MTE@._V1_SY1000_CR0,0,631,1000_AL_.jpg",
                            Price = 119.0,
                            RunTime = "89",
                            Title = "Lucy",
                            TrailerUrl = "https://www.youtube.com/embed/bN7ksFEVO9U",
                            Year = 2014
                        },
                        new
                        {
                            Id = 16,
                            Actors = "Brad Pitt, Edward Norton, Helena Bonham Carter",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5441),
                            Director = "David Fincher",
                            Genre = "Drama",
                            ImdbId = "tt0137523",
                            ImdbRating = 8.8000000000000007,
                            InStock = 7,
                            NoOfOrders = 0,
                            Plot = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more. ",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,666,1000_AL_.jpg",
                            Price = 119.0,
                            RunTime = "139",
                            Title = "Fight Club",
                            TrailerUrl = "https://www.youtube.com/embed/qtRKdVHc-cE",
                            Year = 1999
                        },
                        new
                        {
                            Id = 17,
                            Actors = "Russel Crowe, Joaquin Phoenix, Connie Nielsen",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5445),
                            Director = "Ridley Scott",
                            Genre = "Action, Drama, Adventure",
                            ImdbId = "tt0172495",
                            ImdbRating = 8.5,
                            InStock = 12,
                            NoOfOrders = 0,
                            Plot = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,675,1000_AL_.jpg",
                            Price = 109.0,
                            RunTime = "155",
                            Title = "Gladiator",
                            TrailerUrl = "https://www.youtube.com/embed/Q-b7B8tOAQU",
                            Year = 2000
                        },
                        new
                        {
                            Id = 18,
                            Actors = "Elisabeth Moss, Oliver Jackson-Cohen, Harriet Dyer",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5449),
                            Director = "Leigh Whannell",
                            Genre = "Horror, Mystery, Sci-Fi",
                            ImdbId = "tt1051906",
                            ImdbRating = 7.0999999999999996,
                            InStock = 35,
                            NoOfOrders = 0,
                            Plot = "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BZjFhM2I4ZDYtZWMwNC00NTYzLWE3MDgtNjgxYmM3ZWMxYmVmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,631,1000_AL_.jpg",
                            Price = 229.0,
                            RunTime = "124",
                            Title = "The Invisible Man",
                            TrailerUrl = "https://www.youtube.com/embed/Pso0Aj_cTh0",
                            Year = 2020
                        },
                        new
                        {
                            Id = 19,
                            Actors = "Ward Horton, Annabelle Wallis, Alfre Woodard",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5454),
                            Director = "John R. Leonetti",
                            Genre = "Horror, Mystery, Thriller",
                            ImdbId = "tt3322940",
                            ImdbRating = 5.4000000000000004,
                            InStock = 16,
                            NoOfOrders = 0,
                            Plot = "A couple begins to experience terrifying supernatural occurrences involving a vintage doll shortly after their home is invaded by satanic cultists.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BOTQwZmQyYzEtODk5ZC00OTY3LWExMjAtYzRjNWFhNGM3MzBlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
                            Price = 129.0,
                            RunTime = "109",
                            Title = "Annabelle",
                            TrailerUrl = "https://www.youtube.com/embed/paFgQNPGlsg",
                            Year = 2014
                        },
                        new
                        {
                            Id = 20,
                            Actors = "Patrick Wilson, Vera Farmiga, Ron Livingston",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5458),
                            Director = "James Wan",
                            Genre = "Horror, Mystery, Thriller",
                            ImdbId = "tt1457767",
                            ImdbRating = 7.5,
                            InStock = 22,
                            NoOfOrders = 0,
                            Plot = "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
                            Price = 149.0,
                            RunTime = "112",
                            Title = "The Conjuring",
                            TrailerUrl = "https://www.youtube.com/embed/k10ETZ41q5o",
                            Year = 2013
                        },
                        new
                        {
                            Id = 21,
                            Actors = "Kang-ho Son, Sun-Kyun Lee, Yeo-Yeong Jo",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5463),
                            Director = "Bong Joon Ho",
                            Genre = "Comedy, Drama, Thriller",
                            ImdbId = "tt6751668",
                            ImdbRating = 8.5999999999999996,
                            InStock = 30,
                            NoOfOrders = 0,
                            Plot = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan. ",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
                            Price = 199.0,
                            RunTime = "132",
                            Title = "Parasite",
                            TrailerUrl = "https://www.youtube.com/embed/5xH0HfJHsaY",
                            Year = 2019
                        },
                        new
                        {
                            Id = 22,
                            Actors = "Jesse Eisenberg, Mark Ruffalo, Woody Harrelson",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5470),
                            Director = "Louis Leterrier",
                            Genre = "Crime, Mystery, Thriller",
                            ImdbId = "tt1670345",
                            ImdbRating = 7.2999999999999998,
                            InStock = 18,
                            NoOfOrders = 0,
                            Plot = "An F.B.I. Agent and an Interpol Detective track a team of illusionists who pull off bank heists during their performances, and reward their audiences with the money. ",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTY0NDY3MDMxN15BMl5BanBnXkFtZTcwOTM5NzMzOQ@@._V1_SY1000_CR0,0,642,1000_AL_.jpg",
                            Price = 99.0,
                            RunTime = "115",
                            Title = "Now You See Me",
                            TrailerUrl = "https://www.youtube.com/embed/4OtM9j2lcUA",
                            Year = 2013
                        },
                        new
                        {
                            Id = 23,
                            Actors = "Robert Downey Jr., Chris Evans, Scarlett Johansson",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5515),
                            Director = "Joss Whedon",
                            Genre = "Action, Adventure, Sci-Fi",
                            ImdbId = "tt0848228",
                            ImdbRating = 8.0,
                            InStock = 21,
                            NoOfOrders = 0,
                            Plot = "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity. ",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_CR0,0,675,1000_AL_.jpg",
                            Price = 129.0,
                            RunTime = "143",
                            Title = "The Avengers",
                            TrailerUrl = "https://www.youtube.com/embed/hIR8Ar-Z4hw",
                            Year = 2012
                        },
                        new
                        {
                            Id = 24,
                            Actors = "Chris Hemsworth, Tom Hiddleston, Cate Blanchett",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5520),
                            Director = "Taika Waititi",
                            Genre = "Action, Adventure, Comedy",
                            ImdbId = "tt3501632",
                            ImdbRating = 7.9000000000000004,
                            InStock = 39,
                            NoOfOrders = 0,
                            Plot = "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela. ",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
                            Price = 179.0,
                            RunTime = "130",
                            Title = "Thor Ragnarök",
                            TrailerUrl = "https://www.youtube.com/embed/v7MGUNV8MxU",
                            Year = 2017
                        },
                        new
                        {
                            Id = 25,
                            Actors = "Daniel Radcliffe, Rupert Grint, Emma Watson",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5524),
                            Director = "Chris Columbus",
                            Genre = "Adventure, Family, Fantasy",
                            ImdbId = "tt0241527",
                            ImdbRating = 7.5999999999999996,
                            InStock = 14,
                            NoOfOrders = 0,
                            Plot = "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world. ",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
                            Price = 109.0,
                            RunTime = "152",
                            Title = "Harry Potter and the Philosophers Stone",
                            TrailerUrl = "https://www.youtube.com/embed/VyHV0BRtdxo",
                            Year = 2001
                        },
                        new
                        {
                            Id = 26,
                            Actors = "Hitoshi Takagi, Noriko Hidaka, Chika Sakamoto",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5529),
                            Director = "Hayao Miyazaki",
                            Genre = "Animation, Family, Fantasy",
                            ImdbId = "tt0096283",
                            ImdbRating = 8.1999999999999993,
                            InStock = 28,
                            NoOfOrders = 0,
                            Plot = "When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BYzJjMTYyMjQtZDI0My00ZjE2LTkyNGYtOTllNGQxNDMyZjE0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            Price = 79.0,
                            RunTime = "86",
                            Title = "My Neighbour Totoro",
                            TrailerUrl = "https://www.youtube.com/embed/92a7Hj0ijLs",
                            Year = 1988
                        },
                        new
                        {
                            Id = 27,
                            Actors = "Chieko Baishô, Takuya Kimura, Tatsuya Gashûin",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5533),
                            Director = "Hayao Miyazaki",
                            Genre = "Animation, Adventure, Family",
                            ImdbId = "tt0347149",
                            ImdbRating = 8.1999999999999993,
                            InStock = 25,
                            NoOfOrders = 0,
                            Plot = "When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNmM4YTFmMmItMGE3Yy00MmRkLTlmZGEtMzZlOTQzYjk3MzA2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_CR0,0,666,1000_AL_.jpg",
                            Price = 79.0,
                            RunTime = "119",
                            Title = "Howl's Moving Castle",
                            TrailerUrl = "https://www.youtube.com/embed/yUZCo0oWt4o",
                            Year = 2004
                        },
                        new
                        {
                            Id = 28,
                            Actors = "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5539),
                            Director = "Hayao Miyazaki",
                            Genre = "Animation, Adventure, Family",
                            ImdbId = "tt0245429",
                            ImdbRating = 8.5999999999999996,
                            InStock = 18,
                            NoOfOrders = 0,
                            Plot = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
                            Price = 79.0,
                            RunTime = "125",
                            Title = "Spirited Away",
                            TrailerUrl = "https://www.youtube.com/embed/qCgon52mp2M",
                            Year = 2001
                        },
                        new
                        {
                            Id = 29,
                            Actors = "Björn A. Ling, Kjell Bergqvist, Tuva Novotny",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5544),
                            Director = "Ulf Malmros",
                            Genre = "Comedy, Drama, Romance",
                            ImdbId = "tt1359421",
                            ImdbRating = 5.9000000000000004,
                            InStock = 3,
                            NoOfOrders = 0,
                            Plot = "When the factory in Molkom shuts down, Robin leaves his beloved hometown to try his luck in Stockholm as a wedding photographer. This experience changes not merely his outlook on life but also his hairstyle.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BYzgxMTU3YjEtZjQ2NS00MTA5LTk3ZTItMzkyODI3NTMzYTM5XkEyXkFqcGdeQXVyMTQzMjU1NjE@._V1_.jpg",
                            Price = 79.0,
                            RunTime = "113",
                            Title = "Bröllopsfotografen",
                            TrailerUrl = "https://www.youtube.com/embed/j2Ai6zAzkOQ",
                            Year = 2009
                        },
                        new
                        {
                            Id = 30,
                            Actors = "Tuva Novotny, Jonas Rimeika, Björn A. Ling",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5548),
                            Director = "Ulf Malmros",
                            Genre = "Comedy, Crime, Mystery",
                            ImdbId = "tt0323998",
                            ImdbRating = 6.9000000000000004,
                            InStock = 5,
                            NoOfOrders = 0,
                            Plot = "A young man returns to his hometown to look for his missing sister.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTMxMTEwNzI3Nl5BMl5BanBnXkFtZTcwMzQ1ODkyMQ@@._V1_.jpg",
                            Price = 79.0,
                            RunTime = "117",
                            Title = "Smala Sussie",
                            TrailerUrl = "https://www.youtube.com/embed/Q8Drrm6Mlco",
                            Year = 2003
                        },
                        new
                        {
                            Id = 31,
                            Actors = "Tom Hardy, Charlize Theron, Nicholas Hoult",
                            AddedToStoreDate = new DateTime(2020, 6, 2, 21, 58, 52, 790, DateTimeKind.Local).AddTicks(5552),
                            Director = "George Miller",
                            Genre = "Action, Adventure, Sci-Fi",
                            ImdbId = "tt1392190",
                            ImdbRating = 8.0999999999999996,
                            InStock = 20,
                            NoOfOrders = 0,
                            Plot = "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            Price = 159.0,
                            RunTime = "120",
                            Title = "Mad Max: Fury Road",
                            TrailerUrl = "https://www.youtube.com/embed/hEJnMQG9ev8",
                            Year = 2015
                        });
                });

            modelBuilder.Entity("MarysMajesticMovies.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MarysMajesticMovies.OrderRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderLine")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("PricePerQty")
                        .HasColumnType("float");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderRows");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MarysMajesticMovies.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("MarysMajesticMovies.Order", b =>
                {
                    b.HasOne("MarysMajesticMovies.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("MarysMajesticMovies.OrderRow", b =>
                {
                    b.HasOne("MarysMajesticMovies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarysMajesticMovies.Order", "Order")
                        .WithMany("OrderRows")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
